#!/data/data/com.termux/files/usr/bin/sh

# Set the directory to monitor
DIR=/sdcard/Pictures/Screenshots

# Set the command to execute when a new file is created
CMD="python3 ./plugin/run.py"

# Path to the state file
STATE_FILE="./plugin/state.txt"

# Function to reset the counter
reset_counter() {
    # echo "Resetting counter..."
    echo "COUNTER=0" > "$STATE_FILE"
    echo "THRESHOLD=5" >> "$STATE_FILE"
    # echo "Counter has been reset."
}

# Reset the counter every time the service is enabled
reset_counter


# Use watchexec to monitor the directory
exec watchexec -p -d 2000 -w "$DIR" -e png,jpg,jpeg --fs-events create -- "$CMD"
