#!/data/data/com.termux/files/usr/bin/sh

# Set the directory to monitor
DIR=/sdcard/Pictures/Screenshots

# Set the command to execute when a new file is created
CMD="python3 ./plugin/run.py"

# Use watchexec to monitor the directory
exec watchexec --debounce 2000 -w "$DIR" -e png,jpg,jpeg $CMD